### ISSUE TITLE
great add-on but..

### ISSUE THREAD

**Issue by Qoraiche** [xd4rker/MinerBlock-Firefox#1]
Salam, 
Anktab b darija 😃 
Khoya add-on zwin mais baqi khasso chwia enhancements

Btw, momkin t3tini fach nhadro ana wiyak?
kantsana next updates..

**Comment by xd4rker** [comment]
Alaykom salam,

Ah khasha bzaf, rani sawbtha f nhar lol. Ghi masalitch liha had ayam.
Ila 3ndk twitter ha dyali: https://twitter.com/xd4rker
