### ISSUE TITLE
How does this compare to Firefox's inbuilt crypto miner blocker?

### ISSUE THREAD

**Issue by zingmars** [xd4rker/MinerBlock-Firefox#2]
Mozilla has implemented a crypto miner blocker in Firefox in version 67.0 - https://blog.mozilla.org/futurereleases/2019/04/09/protections-against-fingerprinting-and-cryptocurrency-mining-available-in-firefox-nightly-and-beta/

Other than being newer and probably not having as complete as a blocklist as MinerBlock, how does this feature compare to MinerBlock?

**Comment by xd4rker** [comment]
Minerblock not only uses domain blacklisting, but it also scans the HTML DOM for known cryptomining function calls and kills them. That is the difference.
